@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Apr 16 13:13:31 +0800 2021
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim sim_first_behav -key {Behavioral:sim_1:Functional:sim_first} -tclbatch sim_first.tcl -view D:/project/xxxx/my_subsystem_2/New_NIC1_use_3_ports/sim_first_behav.wcfg -log simulate.log"
call xsim  sim_first_behav -key {Behavioral:sim_1:Functional:sim_first} -tclbatch sim_first.tcl -view D:/project/xxxx/my_subsystem_2/New_NIC1_use_3_ports/sim_first_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
