# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/project/FPGA_New_CC/NIC1_right/imports/xxv_ethernet_0_example_top.xdc

# IP: ip/xxv_ethernet_0_gt_3/xxv_ethernet_0_gt_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xxv_ethernet_0_gt_3 || ORIG_REF_NAME==xxv_ethernet_0_gt_3} -quiet] -quiet

# IP: ip/xxv_ethernet_0_gt_2/xxv_ethernet_0_gt_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xxv_ethernet_0_gt_2 || ORIG_REF_NAME==xxv_ethernet_0_gt_2} -quiet] -quiet

# IP: ip/xxv_ethernet_0_gt_1/xxv_ethernet_0_gt_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xxv_ethernet_0_gt_1 || ORIG_REF_NAME==xxv_ethernet_0_gt_1} -quiet] -quiet

# IP: ip/xxv_ethernet_0_gt_0/xxv_ethernet_0_gt_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xxv_ethernet_0_gt_0 || ORIG_REF_NAME==xxv_ethernet_0_gt_0} -quiet] -quiet

# IP: ip/xxv_ethernet_0/xxv_ethernet_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xxv_ethernet_0 || ORIG_REF_NAME==xxv_ethernet_0} -quiet] -quiet

# XDC: d:/project/FPGA_New_CC/NIC1_right/xxv_ethernet_0_ex.gen/sources_1/ip/xxv_ethernet_0_gt_3/synth/xxv_ethernet_0_gt_3_ooc.xdc

# XDC: d:/project/FPGA_New_CC/NIC1_right/xxv_ethernet_0_ex.gen/sources_1/ip/xxv_ethernet_0_gt_3/synth/xxv_ethernet_0_gt_3.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_0_gt_3 || ORIG_REF_NAME==xxv_ethernet_0_gt_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/project/FPGA_New_CC/NIC1_right/xxv_ethernet_0_ex.gen/sources_1/ip/xxv_ethernet_0_gt_2/synth/xxv_ethernet_0_gt_2_ooc.xdc

# XDC: d:/project/FPGA_New_CC/NIC1_right/xxv_ethernet_0_ex.gen/sources_1/ip/xxv_ethernet_0_gt_2/synth/xxv_ethernet_0_gt_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_0_gt_2 || ORIG_REF_NAME==xxv_ethernet_0_gt_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/project/FPGA_New_CC/NIC1_right/xxv_ethernet_0_ex.gen/sources_1/ip/xxv_ethernet_0_gt_1/synth/xxv_ethernet_0_gt_1_ooc.xdc

# XDC: d:/project/FPGA_New_CC/NIC1_right/xxv_ethernet_0_ex.gen/sources_1/ip/xxv_ethernet_0_gt_1/synth/xxv_ethernet_0_gt_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_0_gt_1 || ORIG_REF_NAME==xxv_ethernet_0_gt_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/project/FPGA_New_CC/NIC1_right/xxv_ethernet_0_ex.gen/sources_1/ip/xxv_ethernet_0_gt_0/synth/xxv_ethernet_0_gt_0_ooc.xdc

# XDC: d:/project/FPGA_New_CC/NIC1_right/xxv_ethernet_0_ex.gen/sources_1/ip/xxv_ethernet_0_gt_0/synth/xxv_ethernet_0_gt_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xxv_ethernet_0_gt_0 || ORIG_REF_NAME==xxv_ethernet_0_gt_0} -quiet] {/inst } ]/inst ] -quiet] -quiet
